name: context
# triggers
on: 
  push
env:
  project: "roboshop"
  component: "catalogue"
  enivornment: dev
  
jobs:
  first-job: #stage
    outputs:
      versions: "${{ steps.version-id.outputs.i-v }}"
    runs-on: ubuntu-latest # agent This is github hosted runner
    steps:
      - name: print env variables #step
        run: |
          echo "Project : $project"
          echo "component : $component"
      - name: print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: add variables
        run: |
          echo "course=Githib-Actions" >> $GITHUB_ENV
          echo "duration=5hrs" >> $GITHUB_ENV
      - name: Access in another step variables
        run: |
          echo "course : $course & courseduration : $duration"

      - name: application version
        id: version-id
        run: |
         echo "i-v=1.0.0" >> GITHUB_OUTPUT
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: access another step output
        run: |
          echo "Image-version: ${{ needs.first-job.outputs.versions }}"
