name: context
# triggers
on: 
  push
env:
  project: "roboshop"
  component: "catalogue"
  enivornment: dev
  
jobs:
  my-job: #stage
    runs-on: ubuntu-latest # agent This is github hosted runner
    steps:
      - name: print env variables #step
        run: |
          echo "Project : $project"
          echo "component : $component"
      - name: print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"