name: call another workflow
on: 
 push:
  branch: 
      - 'main'
jobs:
  feature-pipeline:
    uses: VasarlaSravanthi/workflows/.github/workflows/nodejs-eks-feature.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue'